# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.unibee_api_bean_plan_addon_param import UnibeeApiBeanPlanAddonParam
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiMerchantSubscriptionUpdateReq(BaseModel):
    """
    UnibeeApiMerchantSubscriptionUpdateReq
    """ # noqa: E501
    addon_params: Optional[List[UnibeeApiBeanPlanAddonParam]] = Field(default=None, description="addonParams", alias="addonParams")
    confirm_currency: Optional[StrictStr] = Field(default=None, description="Currency To Be Confirmed，Get From Preview", alias="confirmCurrency")
    confirm_total_amount: Optional[StrictInt] = Field(default=None, description="TotalAmount To Be Confirmed，Get From Preview", alias="confirmTotalAmount")
    effect_immediate: Optional[StrictInt] = Field(default=None, description="Effect Immediate，1-Immediate，2-Next Period", alias="effectImmediate")
    gateway_id: Optional[StrictInt] = Field(default=None, description="Id", alias="gatewayId")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Metadata，Map")
    new_plan_id: StrictInt = Field(description="New PlanId", alias="newPlanId")
    proration_date: StrictInt = Field(description="prorationDate date to start Proration，Get From Preview", alias="prorationDate")
    quantity: StrictInt = Field(description="Quantity")
    subscription_id: StrictStr = Field(description="SubscriptionId", alias="subscriptionId")
    __properties: ClassVar[List[str]] = ["addonParams", "confirmCurrency", "confirmTotalAmount", "effectImmediate", "gatewayId", "metadata", "newPlanId", "prorationDate", "quantity", "subscriptionId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantSubscriptionUpdateReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in addon_params (list)
        _items = []
        if self.addon_params:
            for _item in self.addon_params:
                if _item:
                    _items.append(_item.to_dict())
            _dict['addonParams'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantSubscriptionUpdateReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addonParams": [UnibeeApiBeanPlanAddonParam.from_dict(_item) for _item in obj["addonParams"]] if obj.get("addonParams") is not None else None,
            "confirmCurrency": obj.get("confirmCurrency"),
            "confirmTotalAmount": obj.get("confirmTotalAmount"),
            "effectImmediate": obj.get("effectImmediate"),
            "gatewayId": obj.get("gatewayId"),
            "metadata": obj.get("metadata"),
            "newPlanId": obj.get("newPlanId"),
            "prorationDate": obj.get("prorationDate"),
            "quantity": obj.get("quantity"),
            "subscriptionId": obj.get("subscriptionId")
        })
        return _obj


