# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiMerchantProfileUpdateReq(BaseModel):
    """
    UnibeeApiMerchantProfileUpdateReq
    """ # noqa: E501
    address: Optional[StrictStr] = Field(default=None, description="address")
    company_logo: Optional[StrictStr] = Field(default=None, description="company_logo", alias="companyLogo")
    company_name: Optional[StrictStr] = Field(default=None, description="company_name", alias="companyName")
    email: Optional[StrictStr] = Field(default=None, description="email")
    host: Optional[StrictStr] = Field(default=None, description="User Portal Host")
    phone: Optional[StrictStr] = Field(default=None, description="phone")
    time_zone: Optional[StrictStr] = Field(default=None, description="User TimeZone", alias="timeZone")
    __properties: ClassVar[List[str]] = ["address", "companyLogo", "companyName", "email", "host", "phone", "timeZone"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantProfileUpdateReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantProfileUpdateReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "companyLogo": obj.get("companyLogo"),
            "companyName": obj.get("companyName"),
            "email": obj.get("email"),
            "host": obj.get("host"),
            "phone": obj.get("phone"),
            "timeZone": obj.get("timeZone")
        })
        return _obj


