# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiBeanPaymentTimelineSimplify(BaseModel):
    """
    UnibeeApiBeanPaymentTimelineSimplify
    """ # noqa: E501
    create_time: Optional[StrictInt] = Field(default=None, description="create utc time", alias="createTime")
    currency: Optional[StrictStr] = Field(default=None, description="currency")
    gateway_id: Optional[StrictInt] = Field(default=None, description="gateway id", alias="gatewayId")
    id: Optional[StrictInt] = None
    invoice_id: Optional[StrictStr] = Field(default=None, description="invoice id", alias="invoiceId")
    merchant_id: Optional[StrictInt] = Field(default=None, description="merchant id", alias="merchantId")
    payment_id: Optional[StrictStr] = Field(default=None, description="PaymentId", alias="paymentId")
    status: Optional[StrictInt] = Field(default=None, description="0-pending, 1-success, 2-failure")
    subscription_id: Optional[StrictStr] = Field(default=None, description="subscription id", alias="subscriptionId")
    timeline_type: Optional[StrictInt] = Field(default=None, description="0-pay, 1-refund", alias="timelineType")
    total_amount: Optional[StrictInt] = Field(default=None, description="total amount", alias="totalAmount")
    user_id: Optional[StrictInt] = Field(default=None, description="userId", alias="userId")
    __properties: ClassVar[List[str]] = ["createTime", "currency", "gatewayId", "id", "invoiceId", "merchantId", "paymentId", "status", "subscriptionId", "timelineType", "totalAmount", "userId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanPaymentTimelineSimplify from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanPaymentTimelineSimplify from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createTime": obj.get("createTime"),
            "currency": obj.get("currency"),
            "gatewayId": obj.get("gatewayId"),
            "id": obj.get("id"),
            "invoiceId": obj.get("invoiceId"),
            "merchantId": obj.get("merchantId"),
            "paymentId": obj.get("paymentId"),
            "status": obj.get("status"),
            "subscriptionId": obj.get("subscriptionId"),
            "timelineType": obj.get("timelineType"),
            "totalAmount": obj.get("totalAmount"),
            "userId": obj.get("userId")
        })
        return _obj


