# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.unibee_api_bean_plan_addon_param import UnibeeApiBeanPlanAddonParam
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiMerchantSubscriptionCreatePreviewReq(BaseModel):
    """
    UnibeeApiMerchantSubscriptionCreatePreviewReq
    """ # noqa: E501
    addon_params: Optional[List[UnibeeApiBeanPlanAddonParam]] = Field(default=None, description="addonParams", alias="addonParams")
    gateway_id: StrictInt = Field(description="Id", alias="gatewayId")
    plan_id: StrictInt = Field(description="PlanId", alias="planId")
    quantity: Optional[StrictInt] = Field(default=None, description="Quantity")
    user_id: StrictInt = Field(description="UserId", alias="userId")
    vat_country_code: Optional[StrictStr] = Field(default=None, description="VatCountryCode, CountryName", alias="vatCountryCode")
    vat_number: Optional[StrictStr] = Field(default=None, description="VatNumber", alias="vatNumber")
    __properties: ClassVar[List[str]] = ["addonParams", "gatewayId", "planId", "quantity", "userId", "vatCountryCode", "vatNumber"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantSubscriptionCreatePreviewReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in addon_params (list)
        _items = []
        if self.addon_params:
            for _item in self.addon_params:
                if _item:
                    _items.append(_item.to_dict())
            _dict['addonParams'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantSubscriptionCreatePreviewReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addonParams": [UnibeeApiBeanPlanAddonParam.from_dict(_item) for _item in obj["addonParams"]] if obj.get("addonParams") is not None else None,
            "gatewayId": obj.get("gatewayId"),
            "planId": obj.get("planId"),
            "quantity": obj.get("quantity"),
            "userId": obj.get("userId"),
            "vatCountryCode": obj.get("vatCountryCode"),
            "vatNumber": obj.get("vatNumber")
        })
        return _obj


