# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiBeanVatCountryRate(BaseModel):
    """
    UnibeeApiBeanVatCountryRate
    """ # noqa: E501
    country_code: Optional[StrictStr] = Field(default=None, alias="countryCode")
    country_name: Optional[StrictStr] = Field(default=None, alias="countryName")
    gateway: Optional[StrictStr] = None
    id: Optional[StrictInt] = Field(default=None, description="TaxId")
    standard_tax_percentage: Optional[StrictInt] = Field(default=None, description="Tax税率，万分位，1000 表示 10%", alias="standardTaxPercentage")
    vat_support: Optional[StrictBool] = Field(default=None, description="vat support,true or false", alias="vatSupport")
    __properties: ClassVar[List[str]] = ["countryCode", "countryName", "gateway", "id", "standardTaxPercentage", "vatSupport"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanVatCountryRate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanVatCountryRate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "countryCode": obj.get("countryCode"),
            "countryName": obj.get("countryName"),
            "gateway": obj.get("gateway"),
            "id": obj.get("id"),
            "standardTaxPercentage": obj.get("standardTaxPercentage"),
            "vatSupport": obj.get("vatSupport")
        })
        return _obj


