# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.unibee_internal_logic_gateway_gateway_bean_gateway_balance import UnibeeInternalLogicGatewayGatewayBeanGatewayBalance
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiMerchantBalanceDetailQueryRes(BaseModel):
    """
    UnibeeApiMerchantBalanceDetailQueryRes
    """ # noqa: E501
    available: Optional[List[UnibeeInternalLogicGatewayGatewayBeanGatewayBalance]] = None
    connect_reserved: Optional[List[UnibeeInternalLogicGatewayGatewayBeanGatewayBalance]] = Field(default=None, alias="connectReserved")
    pending: Optional[List[UnibeeInternalLogicGatewayGatewayBeanGatewayBalance]] = None
    __properties: ClassVar[List[str]] = ["available", "connectReserved", "pending"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantBalanceDetailQueryRes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available (list)
        _items = []
        if self.available:
            for _item in self.available:
                if _item:
                    _items.append(_item.to_dict())
            _dict['available'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in connect_reserved (list)
        _items = []
        if self.connect_reserved:
            for _item in self.connect_reserved:
                if _item:
                    _items.append(_item.to_dict())
            _dict['connectReserved'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pending (list)
        _items = []
        if self.pending:
            for _item in self.pending:
                if _item:
                    _items.append(_item.to_dict())
            _dict['pending'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiMerchantBalanceDetailQueryRes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available": [UnibeeInternalLogicGatewayGatewayBeanGatewayBalance.from_dict(_item) for _item in obj["available"]] if obj.get("available") is not None else None,
            "connectReserved": [UnibeeInternalLogicGatewayGatewayBeanGatewayBalance.from_dict(_item) for _item in obj["connectReserved"]] if obj.get("connectReserved") is not None else None,
            "pending": [UnibeeInternalLogicGatewayGatewayBeanGatewayBalance.from_dict(_item) for _item in obj["pending"]] if obj.get("pending") is not None else None
        })
        return _obj


